- id: normalise
  name: Normalise white space
  description: Expand tabs, remove unnecessary whitespace.
  entry: normalise
  language: python
  files: \.(h|hh|H|hp|hxx|hpp|HPP|h\+\+|tcc|cc|cp|cxx|cpp|CPP|c\+\+|C)$
- id: header-guard
  name: Header guard
  description: Add C/C++ header guard
  entry: header-guard
  language: python
  files: \.(h|hh|H|hp|hxx|hpp|HPP|h\+\+|tcc)$
- id: normalise-opencl
  name: Normalise OpenCL keywords
  description: Remove leading underscores from OpenCL keywords
  entry: normalise-opencl
  language: python
  files: \.cl$
- id: normalise-cpp
  name: Normalise C/C++ code
  description: Expand include paths.
  entry: normalise-cpp
  language: python
- id: legal
  name: Copyright and license notices
  description: Add/update copyright and license notices.
  entry: legal
  language: python
  files: \.(h|hh|H|hp|hxx|hpp|HPP|h\+\+|tcc|cc|cp|cxx|cpp|CPP|c\+\+|C)$
  files: \.(h|hh|H|hp|hxx|hpp|HPP|h\+\+|tcc|cc|cp|cxx|cpp|CPP|c\+\+|C)$
